### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by walrusdunne** [walrusdunne/Cheques#1]
- [x] Make data file path configurable
- [x] Make cheque batch size configurable (default: 149)
- [x] Copy both file to local path before reporting (backup to timestamped folder)
- [x] Empty the original files
View previous reports (last 15 days)

**Comment by walrusdunne** [comment]
- [x] Make data file path configurable

ADDED with commit 8de693300fdb730d1ab4a70c2839879674b2710a

**Comment by walrusdunne** [comment]
- [x] Make cheque batch size configurable (default: 149)

ADDED with commit 76c3ab094463e663e557b43ab9efb5809399898d

**Comment by walrusdunne** [comment]
- [x] Copy both file to local path before reporting (backup to timestamped folder)

ADDED with commit 033ad33c71ca7503decc37d27b8953e52ce8934a

**Comment by walrusdunne** [comment]
- [x] Empty the original files

ADDED with commit 12f1d26b342d6798ab28ac345e9e64b9d957bf01

**Comment by walrusdunne** [comment]
View previous reports (last 15 days)

Decided this feature was not required, but could be implemented at a later stage if needed.
